spring:
  application:
    name: ms-ventas-bff
  profiles:
    active: local
  config:
    import: "optional:file:../../.env[.properties],optional:file:./.env[.properties]"

licitawatch:
  internal:
    api-key: ${INTERNAL_API_KEY}
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  swagger-ui:
    path: /swagger-ui.html

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: ${MS_VENTAS_BFF_PORT:8113}
  address: 127.0.0.1
licitawatch:
  servicios:
    ventas-bs: ${VENTAS_BS_URL:http://localhost:8213}
