server:
  address: 127.0.0.1
  port: ${PORT_LICITACIONES:8082}

spring:
  application:
    name: api-licitaciones
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_LICITACIONES:licitaciones_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}

licitawatch:
  notificaciones:
    base-url: http://127.0.0.1:${PORT_NOTIFICACIONES:8084}

logging:
  level:
    cl.licitawatch.licitaciones: INFO
